FROM node:20-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

FROM node:20-alpine AS build
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_GRAPHQL_API_URL
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
ARG NEXT_PUBLIC_GOOGLE_MAPS_ID
ARG NEXT_PUBLIC_LIGHT_GALLERY_LICENSE_KEY
ARG NEXT_PUBLIC_YANDEX_SMARTCAPTCHA_SITE_KEY

ENV NEXT_PUBLIC_GRAPHQL_API_URL=$NEXT_PUBLIC_GRAPHQL_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
ENV NEXT_PUBLIC_GOOGLE_MAPS_ID=$NEXT_PUBLIC_GOOGLE_MAPS_ID
ENV NEXT_PUBLIC_LIGHT_GALLERY_LICENSE_KEY=$NEXT_PUBLIC_LIGHT_GALLERY_LICENSE_KEY
ENV NEXT_PUBLIC_YANDEX_SMARTCAPTCHA_SITE_KEY=$NEXT_PUBLIC_YANDEX_SMARTCAPTCHA_SITE_KEY

ENV NODE_ENV=production
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

ARG NEXT_PUBLIC_GRAPHQL_API_URL
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
ARG NEXT_PUBLIC_GOOGLE_MAPS_ID
ARG NEXT_PUBLIC_LIGHT_GALLERY_LICENSE_KEY
ARG NEXT_PUBLIC_YANDEX_SMARTCAPTCHA_SITE_KEY

COPY package.json package-lock.json ./
RUN npm ci --omit=dev && npm cache clean --force

COPY --from=build /app/public ./public
COPY --from=build /app/.next ./.next

ENV NEXT_PUBLIC_GRAPHQL_API_URL=$NEXT_PUBLIC_GRAPHQL_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
ENV NEXT_PUBLIC_GOOGLE_MAPS_ID=$NEXT_PUBLIC_GOOGLE_MAPS_ID
ENV NEXT_PUBLIC_LIGHT_GALLERY_LICENSE_KEY=$NEXT_PUBLIC_LIGHT_GALLERY_LICENSE_KEY
ENV NEXT_PUBLIC_YANDEX_SMARTCAPTCHA_SITE_KEY=$NEXT_PUBLIC_YANDEX_SMARTCAPTCHA_SITE_KEY

EXPOSE 3000
CMD ["npm", "run", "start"]
